-- MySQL Script generated by MySQL Workbench
-- 05/07/18 08:18:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`place` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(245) NULL,
  `checkins` INT NULL,
  `phone` VARCHAR(20) NULL,
  `website` VARCHAR(245) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`location` (
  `city` VARCHAR(100) NULL,
  `country` VARCHAR(100) NULL,
  `latitude` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  `state` VARCHAR(45) NULL,
  `place_id` INT UNSIGNED NOT NULL,
  INDEX `fk_location_place_idx` (`place_id` ASC),
  CONSTRAINT `fk_location_place`
    FOREIGN KEY (`place_id`)
    REFERENCES `mydb`.`place` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`picture` (
  `height` INT NULL,
  `is_silhouette` TINYINT(1) NULL,
  `url` LONGTEXT NULL,
  `width` INT NULL,
  `place_id` INT UNSIGNED NOT NULL,
  INDEX `fk_picture_place1_idx` (`place_id` ASC),
  CONSTRAINT `fk_picture_place1`
    FOREIGN KEY (`place_id`)
    REFERENCES `mydb`.`place` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
